name: Hotfix Release

on:
  push:
    branches: 
      - 'hotfix/*'

jobs:
  hotfix-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Reset promotion branch
        run: |
          echo ${GITHUB_REF#refs/heads/}
          git fetch origin ${GITHUB_REF#refs/heads/}:${GITHUB_REF#refs/heads/}
          git reset --hard ${GITHUB_REF#refs/heads/}

      # Q: 이미 push가 되어 pull request가 생성되었을 때는 어떻게?
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{github.ref#refs/heads/}}
          delete-branch: true
          assignees: ${{github.actor}}