name: Main Release

on:
  # TODO: push, release 두 가지 모두 사용할 경우 release 시 actions 두번 실행
  # TODO: push로 하면 활용성은 높지만 v*이 아닌 마지막 커밋 명으로 actions 실행
  # push:
  #   tags: [v*]
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |

      # TODO: 디플로이 진행
      - name: Deploy
        run: echo "deploy"

      # TODO: release가 끝난 뒤 다음 버전 Tags를 draft해야함!
