name: Main Release

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.5

      - name: Run when main pushed with tags
        # if: github.ref == 'refs/heads/main'
        run: |
          echo "branch: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
