name: Main Release

on:
  # TODO: push, release 두 가지 모두 사용할 경우 release 시 actions 두번 실행
  # TODO: push로 하면 활용성은 높지만 v*이 아닌 마지막 커밋 명으로 actions 실행
  push:
    tags: [v*]
  # release:
    # TODO: created도 option에 들어가야 할까?
    # types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
