name: Release drafter

on: 
  pull_request:
    # base branch가 main인 경우
    branches: [main]
    # TODO: pull_request가 생성이 되었을 때인지 merge 되었을 때인지 구분 필요
    # merge인 경우 closed 실행 후 if에서 조절해야함
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Release drafter
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: my-config.yml
