name: Release drafter

on: 
  pull_request:
    # base branch가 main인 경우
    # branches: [main]
    # TODO: pull_request가 생성이 되었을 때인지 merge 되었을 때인지 구분 필요
    # merge인 경우 closed 실행 후 if에서 조절해야함
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: check base branch name
        run: echo ${GITHUB_REF##*/}
      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
