name: Release drafter

on:
  #main이 push되었을 때로 바꿀 수 있을듯!! XXXX
  pull_request:
    # base branch가 main인 경우
    # branches: [main]
    # TODO: pull_request가 생성이 되었을 때인지 merge 되었을 때인지 구분 필요
    # merge인 경우 closed 실행 후 if에서 조절해야함
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.ref === 'main'
    steps:
      - name: check base branch name
        run: echo ${{github.ref}}
      # pull request 생성 시 자동으로 label이 설정되도록 한다면? 개발자가 불편하지 않을듯...?
      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
