name: Staging

on:
  # release-note.yml에 들어갈 수 있음 pull request가 끝날 때만 실행되도록
  push:
    branches: [main]

jobs:
  Staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Staging
        run: echo Staging
